<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $this->escape($this->result['title']); ?></title>
</head>
<body>
    <h1><?php echo $this->escape($this->result['h1']) ; ?></h1>
    <form action="post" method="post">
        name:<input type="text" name="name">
        <input type="submit" value="送信">
    </form>
</body>
</html>