<html>
<head>
<title>ユーザ認証</title>
</head>
<body>
<form method="POST" action="/zend/controller_other/auth/process">
<table border="0" align="center">
	<tr>
		<th align="right">ユーザ名：</th>
		<td><input type="text" name="uid" size="10" maxlength="15" /></td>
	</tr><tr>
		<th align="right">パスワード：</th>
		<td><input type="password" name="passwd" size="10" maxlength="15" /></td>
	</tr><tr>
		<td rowspan="2"><input type="submit" name="submit" value="ログイン" /></td>
	</tr>
</table>
</form>
</body>
</html>