<html>
<head>
<title>AjaxContextアクションヘルパー</title>
<script type="text/javascript" src="/zend/controller2/js/jquery.js"></script>
<script type="text/javascript">
<!--
$(
	function() {
		$('#btn').click(
			function() {
				$('#result').load('/zend/controller2/ajax/process/format/html', 
					$('form').serializeArray());
			}
		);
	}
);
//-->
</script>
</head>
<body>
<form method="POST" action="/zend/controller2/ajax/process">
名前：
<input type="text" id="name" name="name" size="10" maxlength="15" />
<input type="button" id="btn" value="送信（Ajax）" />
<input type="submit" value="送信（非Ajax）" />
<div id="result"></div>
</form>
</body>
</html>
